### ISSUE TITLE
User Registration

### ISSUE THREAD

**Issue by chrisvidal** [initbiz/cumuluscore-plugin#44]
the config is as follows:
auto assign user to a cluster, created by the variable `clustername`
cluster auto assign to a plan, trough the variable `plan`

and I received this error, no trace log in system.log

![image](https://user-images.githubusercontent.com/2263496/136931494-2d2d5f78-42f1-4916-9ed0-b27f5db169ce.png)

**Comment by chrisvidal** [comment]
I tried that as well, but still not updating cumulus.core

**Comment by tomaszstrojny** [comment]
Ensure you have the correct version definition in your `composer.json` file. Maybe it's something wrong with it? For more info take  a look here: https://getcomposer.org/doc/articles/versions.md#writing-version-constraints
